<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users [
  <!ELEMENT users (user)>
  <!ELEMENT user (username, password)>
  <!ELEMENT username (#PCDATA)>
  <!ELEMENT password (#PCDATA)>
]>
<users>
  <user>
    <username>mark</username>
    <password>kram</password>
  </user>
  <user>
    <username>user</username>
    <password>pass</password>
  </user>
</users>